version: 0.2
phases:
    install:
        runtime-versions:
            java: corretto8
            docker: 18
        commands:
            - echo Nothing to do in the install phase...
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - export IMAGE_TAG=$(./gradlew properties -q | grep "^version:*" | awk '{print $2}')
    build:
        commands:
            - echo Build started on `date`
            - ./gradlew -Pprod jibDockerBuild
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
cache:
    paths:
        - '/root/.gradle/wrapper/**/*'
        - '/root/.gradle/caches/**/*'
        - '.gradle/**/*'
